// <auto-generated />
namespace mvc_net_Crm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StokHareket : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StokHareket));
        
        string IMigrationMetadata.Id
        {
            get { return "202404281311353_StokHareket"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
